import { IProducts } from '@/interfaces/products.interface'

export const ProductsData: IProducts[] = [
	{
		id: 1,
		image: 'rasberry.svg',
		desc: [
			'Малина 90/10',
			'Цілі ягоди 90%, дріблені 10%',
			'Сорти: Полька, Полана, Джоан Дж.',
			'Упаковка: картонна коробка',
			'Вага: 10 кг',
			'Походження: Україна',
		],
	},
	{
		id: 2,
		image: 'blueberry.png',
		desc: [
			'Чорниця',
			'Сорт: Дика чорниця',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 3,
		image: 'rasberry.svg',
		desc: [
			'Малина 70/30',
			'Цілі ягоди 70%, дріблені 30%',
			'Сорти: Полька, Полана, Джоан Дж.',
			'Упаковка: картонна коробка',
			'Вага: 10 кг',
			'Походження: Україна',
		],
	},
	{
		id: 4,
		image: 'sourCherry.png',
		desc: [
			'Вишня',
			'Сорти: Альфа, Шанс, Елегентна',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 5,
		image: 'rasberry.svg',
		desc: [
			'Малина Мікс',
			'Цілі ягоди 50%, дріблені 50%',
			'Сорти: Полька, Полана, Джоан Дж.',
			'Упаковка: картонна коробка',
			'Вага: 10 кг',
			'Походження: Україна',
		],
	},
	{
		id: 6,
		image: 'blackberry.svg',
		desc: [
			'Ожина',
			'Сорт: Дика ожина',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 7,
		image: 'rasberry.svg',
		desc: [
			'Малина Грис',
			'100% зламана',
			'Сорти: Полька, Полана, Джоан Дж.',
			'Упаковка: картонна коробка',
			'Вага: 10 кг',
			'Походження: Україна',
		],
	},
	{
		id: 8,
		image: 'strawberry.svg',
		desc: [
			'Полуниця некалібрована з кистями',
			'Сорти: Honeoye, Klery',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 9,
		image: 'strawberry.svg',
		desc: [
			'Клубніка калібрована',
			'Розміри: 15/25 мм',
			'Сорти: Honeoye, Klery',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 10,
		image: 'strawberry.svg',
		desc: [
			'Клубніка некалібрована',
			'Сорти: Honeoye, Klery',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 11,
		image: 'cranberry.svg',
		desc: [
			'Журавлина',
			'Сорт: Дика журавлина',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 12,
		image: 'cowberry.svg',
		desc: [
			'Брусниця',
			'Сорт: Дика брусниця',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
	{
		id: 13,
		image: 'roseHip.svg',
		desc: [
			'Шипшина',
			'Сорт: Дика шипшина',
			'Упаковка: картонна коробка та паперовий пакет',
			'Вага: 10 кг; 20 кг; 25 кг',
			'Походження: Україна',
		],
	},
]

export const ProductsDataEn: IProducts[] = [
	{
		id: 1,
		image: 'rasberry.svg',
		desc: [
			'Raspberries 90/10',
			'Whole berries 90%, broken 10%',
			'Varietes: Polka, Polana, Joan J',
			'Packing: carton box',
			'Weight: 10 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 2,
		image: 'blueberry.png',
		desc: [
			'Blueberry',
			'Variety: Wild blueberry',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 3,
		image: 'rasberry.svg',
		desc: [
			'Raspberries 70/30',
			'Whole berries 70%, broken 30%',
			'Varieties: Polka, Polana, Joan J',
			'Packing: carton box',
			'Weight: 10 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 4,
		image: 'sourCherry.png',
		desc: [
			'Sour Cherry',
			'Varieties: Alfa, Chance, Elegentna',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 5,
		image: 'rasberry.svg',
		desc: [
			'Raspberries Mix',
			'Whole berries 50%, broken 50%',
			'Varieties: Polka, Polana, Joan J',
			'Packing: carton box',
			'Weight: 10 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 6,
		image: 'blackberry.svg',
		desc: [
			'Blackberry',
			'Variety: Wild blackberry',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 7,
		image: 'rasberry.svg',
		desc: [
			'Raspberries Crumble',
			'100% broken',
			'Varieties: Polka, Polana, Joan J',
			'Packing: carton box',
			'Weight: 10 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 8,
		image: 'strawberry.svg',
		desc: [
			'Strawberry uncalibrated with strokes',
			'Varieties: Honeoye, Klery',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 9,
		image: 'strawberry.svg',
		desc: [
			'Strawberry calibrated',
			'Dimensions: 15/25 mm',
			'Varieties: Honeoye, Klery',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 10,
		image: 'strawberry.svg',
		desc: [
			'Strawberry uncalibrated',
			'Varieties: Honeoye, Klery',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 11,
		image: 'cranberry.svg',
		desc: [
			'Cranberry',
			'Variety: Wild cranberry',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 12,
		image: 'cowberry.svg',
		desc: [
			'Cowberry',
			'Variety: Wild Cowberry',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
	{
		id: 13,
		image: 'roseHip.svg',
		desc: [
			'Rose Hip',
			'Variety: Wild Rose Hip',
			'Packing: carton box and paper bag',
			'Weight: 10 kg; 20 kg; 25 kg',
			'Origin: Ukraine',
		],
	},
]
